apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-system-api.fullname" . }}
  labels:
    {{- include "notification-system-api.labels" . | nindent 4 }}
type: Opaque
data:
  CONNECTIONSTRINGS__RABBITMQ: {{ .Values.rabbitmq.connectionString | b64enc }}