name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/customer-management-api/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'services/customer-management-api/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file services/customer-management-api/Dockerfile --tag customer-management-api:$(date +%s)
